# Server Port Configuration
server.port=7602

# PostgreSQL database connection configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/ubuntu_health_db
spring.datasource.username=postgres
spring.datasource.password=NjenjeseZ@98
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger custom UI path
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework=DEBUG
spring.security.user.name=admin
spring.security.user.password=admin123